### ISSUE TITLE
Common JS & NPM

### ISSUE THREAD

**Issue by Hiswe** [Canop/JSON.prune#3]
Hi, thank you for this piece of code :)
It just helps me a lot 5 minutes ago.

I was wondering if it was possible to make this a commonJS module and publish it to NPM? 

so we'll be able to make something like 
```js
var prune  = require('json-prune');

prune(obj);
```

Thanks again!

**Comment by Canop** [comment]
Can you review this branch and tell me if it looks OK to you ?
https://github.com/Canop/JSON.prune/tree/npm

If it's OK, I'll register it.

**Comment by Hiswe** [comment]
Hi Canop :)

Thanks for the quick answer!

It seems ok for me :) but you can even improve with a requireJS support.

I think [this patten](https://github.com/umdjs/umd/blob/master/returnExports.js) should fit

**Comment by Hiswe** [comment]
I've forget something: you'll need to provide a package.json in order to publish it on NPM registry ¬_¬'

A `npm init` should generate it. 
The only thing should be the set the `"main"`  to `"JSON.prune.js"`

**Comment by Canop** [comment]
Published: https://www.npmjs.com/package/json-prune

I won't clutter the code for requirejs unless somebody really needs it. I don't think it's the future.

**Comment by Hiswe** [comment]
@Canop That's perfect!
Thank you very much.

For requireJs , with ES6 modules, you should be right :)
