### ISSUE TITLE
functions

### ISSUE THREAD

**Issue by svnpenn** [Canop/JSON.prune#5]
For example, if you visit this page:

http://youtube.com/watch?v=qwspCgEUj64

Request:

    yt.player.Application

Response:

    Object { create: f9.create(), createWebComponent: f9.B() }

However pruned request:

    JSON.pruned(yt.player.Application)

Gives empty response:

    "{}"

**Comment by svnpenn** [comment]
I found a workaround. Request:

~~~
yt.player.Application.toSource()
~~~

Response:

~~~
"({create:(function (a,b){try{var c=f9.C(a);if(f9.j[c]){try{f9.j[c].dispose()}catch(e){Ki(e)}f9.j[c]=null}var d=new f9(a,b);Lb(d,function(){f9.j[c]=null});
return f9.j[c]=d}catch(e){throw Ki(e),e.stack;}}), createWebComponent:(function (a,b){cv("pwc");var c=window.document.querySelector(a);window.document.registerElement(a,{});var d=c.querySelector("template"),c=c.createShadowRoot(),d=window.document.importNode(d.content,!0);c.appendChild(d);c=c.getElementById(b);d=v("ytplayer.config");c=f9.create(c,d);d.loaded=!0;return c})})"
~~~

**Comment by Canop** [comment]
@svnpenn Not serializing functions is the normal behavior (it's also what's done in JSON.stringify). If you want to serialize functions you may use this option of JSON.prune: https://github.com/Canop/JSON.prune#example-4-function-serialization

If you think I misunderstood the issue, please come and discuss it on Miaou: https://dystroy.org/miaou/8

**Comment by svnpenn** [comment]
@Canop no, your suggestion does not work:

~~~
JSON.pruned(yt.player.Application, options)
"{}"
~~~

**Comment by svnpenn** [comment]
@Canop ok your suggestion does work, thank you. However it should be noted that
this script does not work:

http://stackoverflow.com/questions/13861254/json-stringify-deep-objects#14145840

this one does:

http://github.com/Canop/JSON.prune/blob/master/JSON.prune.js

**Comment by svnpenn** [comment]
@Canop ok your suggestion does work, thank you. However it should be noted that
this script does not work:

http://stackoverflow.com/questions/13861254/json-stringify-deep-objects#14145840

this one does:

http://github.com/Canop/JSON.prune/blob/master/JSON.prune.js
